### ISSUE TITLE
Tensorflow-2

### ISSUE THREAD

**Issue by Amin-Tgz** [dragen1860/TensorFlow2.0Tutorials#11]
Hello,
I'm one of the fans of Tensorflow-2 and have created a [repository](https://github.com/Amin-Tgz/Awesome-TensorFlow-2) to collect the best of resources available which use this version.
Recently I saw your fantastic repository and notebooks about TF v2.0.
So I add this to my repo. I appreciate if you can help me to collect other stuff you think might be useful
Thanks.

**Comment by dragen1860** [comment]
Thank you for your reference.
