### ISSUE TITLE
Error while running conv_train.py

### ISSUE THREAD

**Issue by Peter9606** [dragen1860/TensorFlow2.0Tutorials#2]
First of all, thanks for sharing this great resource for tensorflow beginners, really appreciate.

I got an runtime error while trying to run conv_train.py, its output is as following:

Traceback (most recent call last):
  File "./conv_train.py", line 45, in <module>
    print('Dataset  shape: {}'.format(train_ds.output_shapes))

I'm totally unfamiliar with TF api, so can you point me out where I'm wrong?
Thanks

**Comment by dragen1860** [comment]
@Peter9606 bugs resolved. please `git pull` to get latest code. Thank you.
