### ISSUE TITLE
The ordering of batch and repeat

### ISSUE THREAD

**Issue by Haichao-Zhang** [dragen1860/TensorFlow2.0Tutorials#23]
Shall we do repeat before batching?

https://github.com/dragen1860/TensorFlow-2.x-Tutorials/blob/6e95f8707a5ac39aeebf48be8652871990b5600b/03-Play-with-MNIST/main.py#L13

**Comment by dragen1860** [comment]
Hi, please refer to : https://stackoverflow.com/questions/49915925/output-differences-when-changing-order-of-batch-shuffle-and-repeat
