### ISSUE TITLE
Image in the CycleGan tutorial is high noise and does not represent cyclegan

### ISSUE THREAD

**Issue by wiineeth** [dragen1860/TensorFlow2.0Tutorials#4]
The [generated images](https://github.com/dragen1860/TensorFlow2.0Tutorials/tree/master/lesson25-CycleGAN/images) of the cyclegan example are very bad, is it because of not enough epochs? or is it because of the code?

**Comment by dragen1860** [comment]
oh, It's true. maybe you can try to improve it based on this prototype. I need some time to resolve the problem.  Currently a little bit busy, ~~, Thanks for your feedback.
