### ISSUE TITLE
Error in A2C

### ISSUE THREAD

**Issue by maggiezha** [dragen1860/TensorFlow2.0Tutorials#7]
I got this error when I run: python a2c.py
Traceback (most recent call last):
  File "a2c.py", line 135, in <module>
    model = Model(num_actions=env.action_space.n)
  File "a2c.py", line 19, in __init__
    super().__init__('mlp_policy')
TypeError: super() takes at least 1 argument (0 given)

**Comment by dragen1860** [comment]
make sure you use python 3.x and tf 2.0. 
I tested it in my platform without errors.
